# Generated by Django 4.1.1 on 2022-10-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('duration', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(upload_to='course')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='exam_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('no_of_questions', models.IntegerField(default=0)),
                ('total_time', models.TimeField()),
                ('no_of_attempt', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('exam_start_date', models.DateField()),
                ('exam_end_date', models.DateField()),
                ('exam_description', models.CharField(default='', max_length=500)),
                ('is_draft', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.exam')),
            ],
            options={
                'db_table': 'exam_master',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='default', max_length=5000)),
                ('no_of_options', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=1000)),
                ('is_explanation', models.BooleanField(default=False)),
                ('is_image', models.BooleanField(default=False)),
                ('explanation', models.CharField(default='', max_length=1000)),
                ('difficulty_level', models.CharField(default='', max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateField(auto_now=True)),
                ('status', models.CharField(default='', max_length=50)),
                ('remark', models.CharField(default='', max_length=50)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.CharField(default='', max_length=1000)),
                ('correct_answer', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('address', models.CharField(default='', max_length=500, null=True)),
                ('mobile', models.CharField(default='', max_length=10, null=True)),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=50, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='register')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=2000)),
                ('image', models.ImageField(default='', max_length=150, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=2000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='topic_course_allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.topic')),
            ],
            options={
                'db_table': 'topic_course_allocation',
            },
        ),
        migrations.CreateModel(
            name='Subtopics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.topic')),
            ],
            options={
                'db_table': 'Subtopics',
            },
        ),
        migrations.CreateModel(
            name='question_reporting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('reporting_reason', models.CharField(default='', max_length=500)),
                ('remarks', models.CharField(default='', max_length=250)),
                ('is_solved', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.question_bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login')),
            ],
            options={
                'db_table': 'question_reporting',
            },
        ),
        migrations.CreateModel(
            name='question_bank_options',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=1500)),
                ('identifier', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.question_bank')),
            ],
            options={
                'db_table': 'question_bank_options',
            },
        ),
        migrations.AddField(
            model_name='question_bank',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.subject'),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.subtopics'),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.topic'),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('tax', models.IntegerField()),
                ('payment_details', models.CharField(max_length=500)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(default='', max_length=1000)),
                ('expiry_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(default='', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.course')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='exam_question_allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.exam_master')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.question_bank')),
            ],
            options={
                'db_table': 'exam_question_allocation',
            },
        ),
        migrations.AddField(
            model_name='exam_master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login'),
        ),
        migrations.CreateModel(
            name='course_subject_allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.subject')),
            ],
            options={
                'db_table': 'course_subject_allocation',
            },
        ),
        migrations.CreateModel(
            name='course_registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('membership', models.BooleanField(default=True)),
                ('paid_reg_date', models.DateField(auto_now_add=True)),
                ('end_reg_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.course')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login')),
            ],
            options={
                'db_table': 'course_registration',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.exam'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login'),
        ),
        migrations.CreateModel(
            name='contribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explanation', models.CharField(default='', max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.question_bank')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login')),
            ],
            options={
                'db_table': 'contribution',
            },
        ),
    ]
