# Generated by Django 4.1.1 on 2022-10-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank_options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lmsmainapp.question_bank'),
        ),
    ]
