# Generated by Django 4.1.1 on 2022-10-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0002_alter_question_bank_options_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_question_allocation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qid', to='lmsmainapp.question_bank'),
        ),
    ]
