# Generated by Django 4.1.1 on 2022-10-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0006_alter_exam_question_allocation_exam_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_question_allocation',
            name='exam_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.exam_master'),
        ),
    ]
