# Generated by Django 4.1.1 on 2022-10-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0008_question_bank_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
