# Generated by Django 4.1.1 on 2022-10-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0010_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
