# Generated by Django 4.1.1 on 2022-10-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0011_delete_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
