# Generated by Django 4.1.1 on 2022-12-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0015_alter_subject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='videoclass')),
                ('duration', models.CharField(default='', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('videolink', models.CharField(default='', max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.course')),
            ],
            options={
                'db_table': 'video_class',
            },
        ),
    ]
